### ISSUE TITLE
Make Username type configurable

### ISSUE THREAD

**Issue by Wissididom** [GeorgeCiesinski/poke-guesser-bot#104]
This is basically just a reminder issue to:
* Make sure we only use IDs in the Code during the migration. During the migration Usernames will have a descriminator of value 0 returned (e. g. wissididom#0)
* Also Bot names and icons will be unified so there is just one for each application (currently you have one for the app and one for the bot), so the `README.md`'s (at least) screenshots need to be updated. Also each application automatically gets assigned a bot.

Resources:
[Discord Help Center Article](https://support.discord.com/hc/en-us/articles/12620128861463)
[Discord Developer Help Center Article](https://support-dev.discord.com/hc/en-us/articles/13667755828631)

**Comment by Wissididom** [comment]
Probably waiting on the following two PRs to be merged and released before we are able to adjust the code to respect that change:
https://github.com/discordjs/discord.js/pull/9634
https://github.com/discordjs/discord.js/pull/9631

As Discord does not break things yet because we are saving things as IDs (thankfully we changed that in the replit version already) and they are simply returning the pomelo name as username (lowercase, only latin characters and dots and underscores) and 0 as discriminator (the 4 digits after the `#` of a discord name). The update of discord.js would just help us use the Global Display Name instead of the unique pomelo username.

**Comment by Wissididom** [comment]
What should be the prefered name to show when we change it? There is three names that will be available: Username, Display Name and Nickname (where the nickname is per server/guild).

1. Nickname if exists -> Display Name if exists -> Username in any other case
2. Nickname if exists -> Username in any other case
3. Display Name if exists -> Username in any other case
4. Display Name if exists -> Nickname if exists -> Username in any other case
5. Always Username (how it currently is)
6. Make it configurable in the admin settings. But then we would still need a default. Maybe with a command like `/settings name format:<predefined choices list to choose from>`.

The only name that is unique is the Username, there can be multiple people with the same Display Name and the same Nickname.

My preference would be 6 with a default value of 5 so in the default settings there cannot be any impersonation or trolling with display names and nicknames.

**Comment by GeorgeCiesinski** [comment]
This is a very good point. I was going to go with 6 with a default of 1, but I think your concern is valid and we should go with 6/5 instead. The server admins can configure it the way they want that way.

**Comment by Wissididom** [comment]
Resolved in #144
