### ISSUE TITLE
Removal of redundant/not-working code

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/poke-guesser-bot#106]
A number of modules perform a test to see if the guild is available and the guildId is not null. In the event of failure, the bot replies to the interaction with an error message, but this may do nothing because `interaction.guild.available` being null may indicate a server outage so the reply would not work.

```
if (!interaction.guild?.available) {
    await interaction.reply({
        content: 'Guild not available  (help -> help -> interaction.guild.available is either null or false)',
        ephemeral: true
    });
    return;
}
if (!interaction.guildId) {
    await interaction.reply({
        content: 'Internal Server Error (help -> help -> interaction.guildId = null)',
        ephemeral: true
    });
    return;
}
```

Before removing this code I want to double check that it isn't needed. I came up with a few questions we should consider:

First, this code is triggered by an async interaction which would indicate that the server is working during the interaction request. Is it likely for the guild to drop during an interaction? 

In the event that it drops, as the reply likely wouldn't work without an available guild, should we log the error or ignore it as it isn't related to the bot?

Could it be a better solution to replace the guild check with a try/catch instead, since it would essentially attempt the interaction and throw an exception if it failed? 

I will take ownership of the issue, but I wanted your input @Wissididom before I make the changes. Let me know what you think when you have a sec.

**Comment by GeorgeCiesinski** [comment]
@Wissididom do you know how to test the guild not being available or the guildId missing? I don't need this as a jest case, but just to ensure that the new code is working correctly before pushing changes.

**Comment by Wissididom** [comment]
Not really, I just have 2 ideas how it could be working:
 * Call `delete interaction.guild;` and/or `delete interaction.guildId;` or `interaction.guildId = 0;` before checking
 * Invert if condition

**Comment by GeorgeCiesinski** [comment]
Discovered 1 bug and one feature which can result in bug through user error. I tested the develop branch and confirmed these bugs existed in that branch as well. 

#108 & #109
