### ISSUE TITLE
findUser uses findMember and therefore crashes

### ISSUE THREAD

**Issue by Wissididom** [GeorgeCiesinski/poke-guesser-bot#113]
# Describe the bug
When a member left the server it has crashed the bot with e. g. `DiscordAPIError: Unknown Member for User-ID 218326560699187210` because that user left the server when for example requesting the leaderboard.

## Expected behavior
The User is fetched successfully, even without being a server member when using findUser.

## Possible solutions
After research on the official discord.js documentation we just have to use somthing like `message.client.users.fetch(id, {force: false})` instead of `message.guild.members.fetch({ user: ids, force: false});` in findUser. Currently we just call findMember and take it's user object.

**Comment by GeorgeCiesinski** [comment]
Nice find, I completely missed this.
