### ISSUE TITLE
Exception on index when running JEST

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/poke-guesser-bot#98]
# Describe the bug

`index.ts` used `process.emit('SIGINT');` to gracefully exit on Windows, but this functionality was broken once Jest was added into the project. This resulted in the error: 

```
index.ts:123:32 - error TS2769: No overload matches this call.
      The last overload gave the following error.
        Argument of type '0' is not assignable to parameter of type 'Signals'.
```

However, the remaining files seemed to work correctly and the tests completed successfully once the line was commented out. 

## To Reproduce

1) Go to `index.ts` and uncomment the line from: 

```typescript
// Gracefully disconnect Postgres-Client on exit
if (process.platform === 'win32') {
    let rl = require('readline').createInterface({
        input: process.stdin,
        output: process.stdout
    });
    rl.on("SIGINT", () => {
        // process.emit('SIGINT', 0);
        process.exit();
    });
}
```

2) Run the tests in the terminal with `npm test`

## Expected behavior

This code worked correctly before Jest and dependencies were added, so the tests should run successfully. The pokebot itself should also function with this line and exit gracefully in windows. 

## Possible solutions
The function seems to expect a `Signals` type parameter so more research needs to be done into this function in typescript to see if there was an error in the code.

**Comment by Wissididom** [comment]
Merged in https://github.com/GeorgeCiesinski/poke-guesser-bot/pull/105
