### ISSUE TITLE
Set up automated unit testing in github actions

### ISSUE THREAD

**Issue by GeorgeCiesinski** [GeorgeCiesinski/poke-guesser-bot#99]
Note: This issue should be done after creating some unit tests.

# Describe the new feature
Github Actions should automatically run the Jest tests on pushes and pull requests.

## Describe alternatives you've considered
Travis CI and other CI tools. Ideally, a free CI should be used.

**Comment by Wissididom** [comment]
Merged in https://github.com/GeorgeCiesinski/poke-guesser-bot/pull/105
